inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  Include:
    - 'Appraisals'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.gemfile'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/*.rb'
  Exclude:
    - 'gemfiles/**/*.gemfile'
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/ArgumentAlignment:
  EnforcedStyle: 'with_fixed_indentation'

Layout/DotPosition:
  EnforcedStyle: 'trailing'

Layout/HashAlignment:
  EnforcedColonStyle: 'table'
  EnforcedHashRocketStyle: 'table'

Layout/LineLength:
  Exclude:
    - 'app/controllers/**/*'
    - 'config/initializers/devise.rb'

Layout/ParameterAlignment:
  EnforcedStyle: 'with_fixed_indentation'

Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'config/routes.rb'
    - 'spec/factories/**/*'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: 'no_space'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Naming/MethodParameterName:
  AllowedNames:
    # defaults:
    - io
    - id
    - to
    - by
    - 'on'
    - in
    - at
    - ip
    - db
    - os
    - pp
    # emjot additions:
    - q
    - dj

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'
  AllowedIdentifiers:
    # defaults (as of rubocop 1.9.1):
    - capture3     # Open3.capture3
    - iso8601      # Time#iso8601
    - rfc1123_date # CGI.rfc1123_date
    - rfc822       # Time#rfc822
    - rfc2822      # Time#rfc2822
    - rfc3339      # DateTime.rfc3339
    # emjot additions:
    - html5
    - s3

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'

RSpec/DescribedClass:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: 'single_statement_only'

RSpec/LetSetup:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'

Style/FormatStringToken:
  Enabled: false # too many false positives in version 0.49.1; see e.g. https://github.com/bbatsov/rubocop/issues/4425

Style/RescueStandardError:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SoleNestedConditional:
  AllowModifier: true
