name: Lint & Test

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: sudo apt-get install -y libsqlite3-dev
      - uses: actions/checkout@master
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8
      - name: Install bundle
        run: bundle
      - name: Run rubocop
        run: bundle exec rubocop
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7.8
          - 3.0.6
          - 3.1.4
          - 3.2.3
        appraisal:
          - rails_5.2_pc_7.1
          - rails_5.2_pc_7.2
          - rails_6.0_pc_7.1
          - rails_6.0_pc_7.2
          - rails_6.1_pc_7.1
          - rails_6.1_pc_7.2
          - rails_7.0_pc_7.1
          - rails_7.0_pc_7.2
          - rails_7.1_pc_7.1
          - rails_7.1_pc_7.2
        exclude:
          - ruby: 3.0.6
            appraisal: rails_5.2_pc_7.1
          - ruby: 3.0.6
            appraisal: rails_5.2_pc_7.2
          - ruby: 3.1.4
            appraisal: rails_5.2_pc_7.1
          - ruby: 3.1.4
            appraisal: rails_5.2_pc_7.2
          - ruby: 3.2.3
            appraisal: rails_5.2_pc_7.1
          - ruby: 3.2.3
            appraisal: rails_5.2_pc_7.2
          - ruby: 2.7.8
            appraisal: rails_7.0_pc_7.1
          - ruby: 2.7.8
            appraisal: rails_7.0_pc_7.2
          - ruby: 2.7.8
            appraisal: rails_7.1_pc_7.1
          - ruby: 2.7.8
            appraisal: rails_7.1_pc_7.2
    steps:
      - name: Install system dependencies
        run: sudo apt-get install -y libsqlite3-dev
      - uses: actions/checkout@master
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 2.4
      - name: Install bundle
        run: bundle
      - name: Install appraisal
        run: bundle exec appraisal install
      - name: Run tests
        run: bundle exec appraisal ${{ matrix.appraisal }} rspec
