name: Lint & Test

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: sudo apt-get install -y libsqlite3-dev
      - uses: actions/checkout@master
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.6
          bundler: 2.5
      - name: Install bundle
        run: bundle
      - name: Run rubocop
        run: bundle exec rubocop
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.0.6
          - 3.1.4
          - 3.2.6
          - 3.3.6
        appraisal:
          - rails_6.1
          - rails_7.0
          - rails_7.1
    steps:
      - name: Install system dependencies
        run: sudo apt-get install -y libsqlite3-dev
      - uses: actions/checkout@master
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 2.5
      - name: Install bundle
        run: bundle
      - name: Install appraisal
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle install
      - name: Run tests
        run: bundle exec appraisal ${{ matrix.appraisal }} rspec
